---
namespace: lagomvpn
name: remnawave
version: 1.0.0
readme: README.md
authors:
  - LagomVPN Team
description: Ansible collection with Remnawave node role for Docker deployment
license:
  - MIT
tags:
  - vpn
  - docker
  - networking
  - proxy
  - security
  - collection
dependencies: {}
repository: https://github.com/Lagom-VPN/ansible-remnawave
documentation: https://github.com/Lagom-VPN/ansible-remnawave/blob/main/README.md
homepage: https://lagomvpn.com
issues: https://github.com/Lagom-VPN/ansible-remnawave/issues
build_ignore:
  - "*.pyc"
  - "*.retry"
  - ".git"
  - ".gitignore"
  - ".DS_Store"
  - "Thumbs.db"
  - "group_vars/"
  - "host_vars/" 