---
- name: Check if docker compose CLI plugin is available
  ansible.builtin.shell: docker compose version
  register: remnanode_compose_check
  changed_when: false
  failed_when: false

- name: Fail if docker compose v2 is missing
  ansible.builtin.fail:
    msg: |
      Docker Compose v2 is required but not found.
      Please install docker compose.
  when: remnanode_compose_check.rc != 0
