galaxy_info:
  role_name: remnanode
  namespace: lagomvpn
  author: LagomVPN Team
  description: Ansible role for deploying Remnawave nodes
  company: LagomVPN
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - vpn
    - docker
    - networking
    - proxy
    - security

dependencies: []

collections:
  - community.docker
